apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('<int:course_id>/', views.course_detail, name='course_detail'),
    path('course_token/', views.course_token, name='course_token'),
    path('course_order/<int:course_id>', views.course_order, name='course_order'),
]

commercial_site/urls.py
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #index page: and also the news index page
    path('', views.index, name='index'),
    #other news pages
    path('news/', include("apps.news.urls")),
    #search page
    path('search/', views.news_search, name='news_search'),
    #cms pages
    path('cms/', include("apps.cms.urls")),
    #authentication page
    path('account/', include("apps.stauth.urls")),
    #course page
    path('course/', include("apps.course.urls")),
    #premium page
    path('premium/', include("apps.premium.urls")),
    #ueditor page
    path('ueditor/', include("apps.ueditor.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

apps/course/models.py
from django.db import models

class CourseCategory(models.Model):
    name = models.CharField(max_length=50)

class Teacher(models.Model):
    username = models.CharField(max_length=100)
    avatar = models.URLField()
    jobtitle = models.CharField(max_length=100)
    profile = models.TextField()

class Course(models.Model):
    title = models.CharField(max_length=100)
    category = models.ForeignKey('CourseCategory', on_delete=models.DO_NOTHING)
    teacher = models.ForeignKey('Teacher', on_delete=models.DO_NOTHING)
    video_url = models.URLField()
    cover_url = models.URLField()
    price = models.FloatField()
    duration = models.IntegerField()
    profile = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)

class CourseOrder(models.Model):
    course = models.ForeignKey("Course", on_delete=models.DO_NOTHING)
    buyer = models.ForeignKey("stauth.User", on_delete=models.DO_NOTHING)
    amount = models.FloatField(default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    # 1：支付宝，2.微信支付
    istype = models.SmallIntegerField(default=0)
    # 1 means not paid yet, 2.sucessfully paid
    status = models.SmallIntegerField(default=1)

apps/course/forms.py
from apps.forms import FormMixin
from django import forms
from .models import Course

class PubCourseForm(forms.ModelForm, FormMixin):
    category_id = forms.IntegerField()
    teacher_id = forms.IntegerField()
    class Meta:
        model = Course
        exclude = ['category', 'teacher']

apps/course/views.py
from django.shortcuts import render
from .models import Course, CourseOrder
from django.shortcuts import get_object_or_404
import time, hmac, os, hashlib
from django.conf import settings
from utils import restful
from apps.stauth.decorators import st_login_required

# Create your views here.
def course_index(request):
    context = {
        'courses': Course.objects.all()
    }
    return render(request, 'course/course_index.html', context=context)

def course_detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    context ={
        'course': course
    }
    return render(request, 'course/course_detail.html', context=context)

def course_token(request):
    # video：是视频文件的完整链接
    file = request.GET.get('video')

    '''course_id = request.GET.get('course_id')
    if not CourseOrder.objects.filter(course_id=course_id,buyer=request.user,status=2).exists():
        return restful.params_error(message='请先购买课程！')'''

    expiration_time = int(time.time()) + 2 * 60 * 60

    USER_ID = settings.BAIDU_CLOUD_USER_ID
    USER_KEY = settings.BAIDU_CLOUD_USER_KEY

    # file=http://hemvpc6ui1kef2g0dd2.exp.bcevod.com/mda-igjsr8g7z7zqwnav/mda-igjsr8g7z7zqwnav.m3u8
    extension = os.path.splitext(file)[1]
    media_id = file.split('/')[-1].replace(extension, '')

    # unicode->bytes=unicode.encode('utf-8')bytes
    key = USER_KEY.encode('utf-8')
    message = '/{0}/{1}'.format(media_id, expiration_time).encode('utf-8')
    signature = hmac.new(key, message, digestmod=hashlib.sha256).hexdigest()
    token = '{0}_{1}_{2}'.format(signature, USER_ID, expiration_time)
    return restful.result(data={'token': token})

@st_login_required
def course_order(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    order = CourseOrder.objects.create(course=course, buyer=request.user, 
    status=1, amount=course.price)
    context ={
        'course': course,
        'order': order,
    }
    return render(request, 'course/course_order.html', context=context)

front/templates/course/course_detail.html
{% extends 'base/front_base.html' %}


{% block head %}
    <link rel="stylesheet" href="{% static 'css/course/course_detail.min.css'%}">
    <script src="{% static 'videojs/video.min.js' %}"></script>
    <script src="{% static 'videojs/videojs-contrib-hls.min.js' %}"></script>
    <script src="{% static 'videojs/videojs-contrib-quality-levels.min.js' %}"></script>
    <script type="text/javascript" src="https://cdn.bdstatic.com/jwplayer/latest/cyberplayer.js"></script>
    <script src="{% static 'js/course_detail.min.js' %}"></script>
{% endblock head %}


{% block title %}
    ST | Course Video
{% endblock title %}


{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="nav-container">
                <h3 class="nav-title">Streaming Table</h3>
                <ul class="nav-list">
                    <li class="active"><a href="#">Recent Courses</a></li>
                    <li><a href="#">Treading Courses</a></li>
                    <li><a href="#">Case Study</a></li>
                    <li><a href="#">Knowledge</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <div class="course-wrapper">
                <div class="course-info">
                    <p class="course-title">{{ course.title }}</p>
                    <div class="price-group">
                        <div class="share-group">
                            <span class="title">Share on:</span>
                            <a href="#" class="facebook share-items"><i class="iconfont icon-Facebooklogo"></i></a>
                            <a href="#" class="twitter share-items"><i class="iconfont icon-twitterlogo"></i></a>
                            <a class="wechat share-items"><i class="iconfont icon-wechat"></i></a>
                        </div>
                        <div class="buy-group">
                            <!--<span class="price pay">$59.99</span>
                            <a href="" class="buy-btn">Join Course</a>-->
                            {% if course.price > 0 %}
                            <span class="price pay">$ {{ course.price }}</span>
                            <a href="{% url 'course:course_order' course_id=course.pk %}" class="buy-btn">Join Course</a>
                            {% else %}
                            <span class="price free">Free</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="video-group">
                    <span hidden id="video-info" data-video-url="{{ course.video_url }}" data-cover-url="{{ course.cover_url }}"></span>
                    <div id="playercontainer">
                    </div>
                </div>
            </div>
            <div class="bottom-wrapper">
                <div class="course-left">
                    <div class="item-group">
                        <p class="item-title">Lecturer</p>
                        <div class="teacher-profile">
                            <div class="avatar-group">
                                <img src="{{ course.teacher.avatar }}" alt="avatar" class="avatar">                                    
                            </div>
                            <div class="teacher-info">
                                    <p>{{ course.teacher.username }}</p>
                            </div>
                        </div>
                        <p class="item-content"> 
                        {{ course.teacher.profile }}
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">Course Description</p>
                        <p class="item-content">
                        {{ course.profile|safe }}
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">Course Outline</p>
                        <p class="item-content"> Include these words in your bio. 
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">Course for</p>
                        <p class="item-content"> if your research focuses on recent changes in ritual music
performed by women of minority groups in South Asia, then your key terms might include:
gender, globalization, modernity, ethnic minority, indigeneity, performance, ritual, and
embodied epistemology. Include these words in your bio. 
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">Help Center</p>
                        <p class="item-content">Your key terms might include:
gender, globalization, modernity, ethnic minority, indigeneity, performance, ritual, and
embodied epistemology. Include these words in your bio. 
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">About Streaming Table</p>
                        <p class="item-content"> Sean Li was born in Jan 1990. Graduated from Benedictine University in MIS. Basic information: Include who you are, what you do, where you’ve worked and studied,
and why you’re worth noticing.
                        </p>
                    </div>
                </div>
                <div class="recommend-right">
                    <p class="item-title">Recommend Course</p>
                    <ul class="course-list">
                        <li>
                            <div class="info">
                                <p class="title">
                                    How to capture light?
                                </p>
                                <p class="teacher">
                                    Sean Li
                                </p>
                            </div>
                            <div class="thumbnail">
                                <img src="{% static 'images/thumbnail2.jpg'%}" alt="">
                            </div>
                        </li>
                        <li>
                            <div class="info">
                                <p class="title">
                                    How to capture light?
                                </p>
                                <p class="teacher">
                                    Sean Li
                                </p>
                            </div>
                            <div class="thumbnail">
                                <img src="{% static 'images/thumbnail2.jpg'%}" alt="">
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}
    
    
    

front/templates/course/course_index.html
{% extends 'base/front_base.html' %}


{% block head %} 
    <link rel="stylesheet" href="{% static 'css/course/course_index.min.css'%}">
{% endblock head %}


{% block title %}
    ST | Course Streaming
{% endblock title %}


{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="nav-container">
                <h3 class="nav-title">Streaming Table</h3>
                <ul class="nav-list">
                    <li class="active"><a href="#">Recent Courses</a></li>
                    <li><a href="#">Treading Courses</a></li>
                    <li><a href="#">Case Study</a></li>
                    <li><a href="#">Knowledge</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <ul class="course-list">
                {% for course in courses %}
                <li>
                    <a href="{% url 'course:course_detail' course_id=course.pk %}">
                        <div class="thumbnail-group">
                            <img src="{{ course.cover_url }}" alt="{{ course.title }}" style="height:123px">
                        </div>
                        <div class="course-info">
                            <p class="title">{{ course.title }}</p>
                            <p class="author">{{ course.teacher.username }}</p>
                            <p class="price-group">
                                
                                {% if course.price > 0 %}
                                <span class="pay">$ {{ course.price }}</span>
                                {% else %}
                                <span class="free">Free Course</span>
                                {% endif %}
                                    
                            </p>
                        </div>
                    </a>
                </li>
                {% endfor %}                
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
    </div>
{% endblock main %}
    
    

front/templates/course/course_order.html
{% extends 'base/front_base.html' %}

{% block title %}
Confirm Order
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/common/header.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/common/footer.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/common/body.min.css' %}">
    <style>
        .table{
            width: 100%;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            background: #eaeaea;
            text-align: center;
        }
        .table{
            border-spacing: 20px;
        }
        .table img{
            width: 120px;
            height: 68px;
            float: left;
        }
        .table .title{
            margin-left: 10px;
        }
        .pay-way label{
            float: right;
        }
        .pay-way span{
            border: 1px solid #ccc;
            position: relative;
            top: 20px;
        }
        .pay-way .zfb-btn{
            display: inline-block;
            width: 139px;
            height: 48px;
            cursor: pointer;
            background: url("http://study.163.com/res/images/pay/payList.png");
            background-position: -140px 0;
            background-size: 300% 200%;
            margin-right:20px;
        }
        .pay-way .wx-btn{
            display: inline-block;
            width: 139px;
            height: 48px;
            position: relative;
            cursor: pointer;
        }
        .pay-way .wx-btn img{
            top: 12px;
            left: 16px;
            position: absolute;
        }
        .submit-group{
            overflow: hidden;
            padding: 60px 0;
        }
        .submit-btn{
            display: block;
            text-align: center;
            width: 136px;
            height:49px;
            line-height: 49px;
            background: url("http://s.stu.126.net/res/images/pay/payBtns.png?c9b6b849b38cca45b160a96802575ac8") no-repeat 4449px 4449px;
            background-position: 0 -302px;
            border: none;
            cursor: pointer;
            color: #fff;
            font-size: 16px;
            float: right;
        }
        .submit-btn:hover{
            background-position: -139px -302px;
        }
    </style>
    <script>
        $(function () {
            var submitBtn = $("#submit-btn");
            submitBtn.click(function (event) {
                event.preventDefault();
                var goodsname = $("input[name='goodsname']").val();
                var istype = $("input[name='istype']:checked").val();
                var notify_url = $("input[name='notify_url']").val();
                var orderid = $("input[name='orderid']").val();
                var price = $("input[name='price']").val();
                var return_url = $("input[name='return_url']").val();
                stajax.post({
                    'url': '/course/course_order_key/',
                    'data': {
                        'goodsname': goodsname,
                        'istype': istype,
                        'notify_url': notify_url,
                        'orderid': orderid,
                        'price': price,
                        'return_url': return_url
                    },
                    'success': function (result) {
                        if(result['code'] === 200){
                            var key = result['data']['key'];
                            var keyInput = $("input[name='key']");
                            keyInput.val(key);
                            $("#pay-form").submit();
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}

{% block main %}
    <div class="main">
        <div class="wrapper">
            <table class="table">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Item Price($)</th>
                    <th>Total($)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td align="left">
                        <a href="#">
                            <img class="thumbnail" src="{{ course.cover_url }}" alt="">
                            <span class="title">{{ course.title }}</span>
                        </a>
                    </td>
                    <td>{{ course.price }}</td>
                    <td>{{ course.price }}</td>
                </tr>
            </tbody>
        </table>
            <form action="https://pay.bbbapi.com/" method="post" id="pay-form">
                <input type="hidden" name="uid" value="49dc532695baa99e16e01bc0">
                <input type="hidden" name="price" value="{{ course.price }}">
                <input type="hidden" name="notify_url" value="{{ notify_url }}">
                <input type="hidden" name="return_url" value="{{ return_url }}">
                <input type="hidden" name="orderid" value="{{ order.pk }}">
                <input type="hidden" name="orderuid" value="{{ request.user.pk }}">
                <input type="hidden" name="goodsname" value="{{ course.title }}">
                <input type="hidden" name="key" value="">
            <div class="pay-way">
                <label for="istype-wx">
                    <input id="istype-wx" type="radio" name="istype" value="2">
                    <span class="wx-btn">
                        <img src="http://nos.netease.com/test-edu-image/1BD9F69D6760CE1508D2269864AA54F8.png" alt="">
                    </span>
                </label>
                <label for="istype-zfb">
                    <input id="istype-zfb" type="radio" name="istype" value="1" checked>
                    <span class="zfb-btn"></span>
                </label>
                <div style="clear: both;"></div>
            </div>
            <div class="submit-group">
                <input type="submit" value="Pay" id="submit-btn" class="submit-btn">
            </div>
        </form>
        </div>
    </div>
{% endblock %}