apps/cms/urls.py
from django.urls import path
from . import views, course_views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoken, name='qntoken'),
    path('banners/', views.banners, name='banners'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('news_list/', views.NewsListView.as_view(), name='news_list') 
]

# course related url pattern
urlpatterns += [
     path('pub_course/', course_views.PubCourseView.as_view(), name='pub_course'),
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('list/', views.news_list, name='news_list'),
    path('public_comment/', views.public_comment, name='public_comment'),
]

apps/stauth/urls.py
from django.urls import path
from . import views

app_name='stauth'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('img_captcha/', views.img_captcha, name="img_captcha"),
    path('email_captcha/', views.email_captcha, name="email_captcha"),
    path('register/', views.register, name="register"),
]

commercial_site/urls.py
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #index page: and also the news index page
    path('', views.index, name='index'),
    #other news pages
    path('news/', include("apps.news.urls")),
    #search page
    path('search/', views.news_search, name='news_search'),
    #cms pages
    path('cms/', include("apps.cms.urls")),
    #authentication page
    path('account/', include("apps.stauth.urls")),
    #course page
    path('course/', include("apps.course.urls")),
    #premium page
    path('premium/', include("apps.premium.urls")),
    #ueditor page
    path('ueditor/', include("apps.ueditor.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
from apps.forms import FormMixin
from django import forms
from apps.news.models import News, Banner

class EditNewsCategoryForm(forms.Form, FormMixin):
    pk = forms.IntegerField(error_messages={
        "required":"Category ID is missing!"})
    name = forms.CharField(max_length=100)

class WriteNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()
    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']

class EditNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()
    pk = forms.IntegerField()
    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']

class AddBannerForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Banner
        fields = ['priority', 'link_to', 'image_url']

class EditBannerForm(forms.ModelForm, FormMixin):
    pk = forms.IntegerField()
    class Meta:
        model = Banner
        fields = ('priority', 'link_to', 'image_url')

apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View, ListView
from django.views.decorators.http import require_GET, require_POST
from apps.news.models import NewsCategory, News, Banner
from utils import restful
from .forms import EditNewsCategoryForm, WriteNewsForm, AddBannerForm, EditBannerForm, EditNewsForm
import os
from django.conf import settings
import qiniu
from django.utils.timezone import now as aware_now, make_aware
import pytz
from apps.news.serializers import BannerSerializer
from django.core.paginator import Paginator
from datetime import datetime
from urllib import parse

# Create your views here.

@staff_member_required(login_url='index')
def index(request):
    return render(request, 'cms/index.html')

def news_list(request):
    newses = News.objects.select_related('category', 'author').all()
    categories = NewsCategory.objects.all()
    context = {
        'newses': newses,
        'categories': categories,
    }
    return render(request, 'cms/news_list.html', context=context)


class NewsListView(View):
    def get(self, request):
        newses = News.objects.select_related('category', 'author').all()
        # for other filter conditions
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0))
        if start or end:
            if start:
                start_date = datetime.strptime(start, '%m/%d/%Y')
            else:
                start_date = datetime(month=5, day=1, year=2020,)
            
            if end:
                end_date = datetime.strptime(end, '%m/%d/%Y')
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))

        if title:
            newses = newses.filter(title__icontains=title)

        if category_id:
             newses = newses.filter(category__id=category_id)
        # create a new paginator obj, give a object lists, and 
        # the number of data rows we want in a page.
        paginator = Paginator(newses, 2)

        # get current page, from front html's param
        current_page_number = int(request.GET.get('p', 1) or 1)

        # once we have paginator obj, 
        # we can have its page_obj based on its current page number.
        page_obj = paginator.page(current_page_number)

        context={
            'categories': NewsCategory.objects.all(),
            'newses': page_obj.object_list,
            'page_obj':page_obj,
            'paginator':paginator,
            'start': start,
            'end': end,
            'title': title,
            'category_id': category_id,
            'url_query': '&'+parse.urlencode({
                'start':start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or 0
            })
        }
        # run self-define method to get more context we need
        extra_context = self.get_pagination_data(paginator, page_obj)

        # update extra context to the general context
        context.update(extra_context)

        return render(request, 'cms/news_list.html', context=context)

    # self defined method to deal with context we need
    # based on paginator and page_obj
    def get_pagination_data(self, paginator, page_obj, around_count=1):
        current_page = page_obj.number

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_pages = range(current_page-around_count, current_page)
            left_has_more = True
        if current_page >= paginator.num_pages-around_count-1:
            right_pages = range(current_page+1, paginator.num_pages+1)
        else:
            right_pages = range(current_page+1, current_page+around_count+1)
            right_has_more = True

        return {
            'left_pages':left_pages,
            'right_pages':right_pages,
            'current_page':current_page,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'num_pages':paginator.num_pages,
        }


class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')

            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, 
            content=content, category=category, author=request.user)

            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())

class EditNewsView(View):
    def get(self, request):
        news_id = request.GET.get('news_id')
        news = News.objects.get(pk=news_id)
        context = {
            'news':news,
            'categories': NewsCategory.objects.all(),
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            pk = form.cleaned_data.get("pk")
            News.objects.filter(pk=pk).update(title=title, desc=desc, thumbnail=thumbnail, 
            content=content, category=category)
            return restful.ok()
        else: 
            return restful.params_error(message=form.get_errors())

@require_POST
def delete_news(request):
    news_id = request.POST.get('news_id')
    News.objects.get(id=news_id).delete()
    return restful.ok()

@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)

@require_POST
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='The category already exisits!')

@require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='There is no such category')
    else:
        return restful.params_error(message=form.get_errors())

@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.get(pk=pk).delete()
        return restful.ok()
    except:
        return restful.params_error(message='There is no such category')

def banners(request):
    return render(request, 'cms/banners.html')

def banner_list(request):
    banners = Banner.objects.all()
    serializer = BannerSerializer(banners, many=True)
    return restful.result(data=serializer.data)

def add_banner(request):
    form = AddBannerForm(request.POST)
    if form.is_valid():
        new_banner = form.save()
        return restful.result(data={"banner_id":new_banner.pk})
    else:
        return restful.params_error(message=form.get_errors())

def delete_banner(request):
    banner_id = request.POST.get('banner_id')
    Banner.objects.filter(pk=banner_id).delete()
    return restful.ok()

def edit_banner(request):
    form = EditBannerForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        Banner.objects.filter(pk=pk).update(image_url=image_url, 
        link_to=link_to, priority=priority)
        return restful.ok()
    else:
        return restful.params_error(message=form.get_errors())

@require_POST
def upload_file(request):
    file = request.FILES.get('file')
    #get UTC aware time
    datetime = aware_now()
    #create pytz chicago time zone
    tz_chicago = pytz.timezone("America/Chicago")
    #convert UTC aware time to chicago timezone
    chicago_now = datetime.astimezone(tz_chicago)
    #stringfy datetime
    suffix = chicago_now.strftime("%m%d%Y%H%M%S")
    file_name = file.name.split('.')
    name = file_name[0] + suffix + '.' + file_name[1]
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    #url = http://127.0.0.1/settings.MEDIA_URL + name
    url = request.build_absolute_uri(settings.MEDIA_URL+name)
    return restful.result(data={'url':url})

@require_GET
def qntoken(request):

front/templates/cms/base.html

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}{% endblock title %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css'%} ">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/daterangepicker/daterangepicker.css'%}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/summernote/summernote-bs4.css' %}">
  <!-- sweetalert --> 
  <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <!-- jQuery -->
    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- Bootstrap 4 -->
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'adminlte/plugins/sparklines/sparkline.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'adminlte/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'adminlte/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.js'%}"></script>
    <!-- sweetalert js--> 
    <script src="{% static 'sweetalert/sweetalert.min.js'%}"></script>
    <script src="{% static 'js/stalert.min.js' %}"></script>
    <!-- message box js--> 
    <script src="{% static 'js/message.min.js' %}"></script>
    <!-- ajax js--> 
    <script src="{% static 'js/stajax.min.js' %}"></script>
    {% block head %}{% endblock head %}    
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{% static 'images/st_logo.png' %}" alt="ST" class="brand-image img-square elevation-3"
           style="opacity: .8; margin-top: 4px">
      <span class="brand-text font-weight-light">CMS</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'images/avatar.png' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Sean Li</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="{% url 'cms:index' %}" class="nav-link active">
              <i class="nav-icon fas fa-home"></i><p>Home</p>
            </a>
          </li>
          <li class="nav-header">Articles</li>
          <li class="nav-item">
            <a href="{% url 'cms:write_news' %}" class="nav-link">
              <i class="nav-icon fas fa-edit"></i><p>Posts</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'cms:news_list' %}" class="nav-link">
              <i class="nav-icon fas fa-list"></i><p>Article List</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'cms:news_category' %}" class="nav-link">
              <i class="nav-icon fas fa-tag"></i><p>Categories</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'cms:banners' %}" class="nav-link">
              <i class="nav-icon fas fa-window-restore"></i><p>Banners</p>
            </a>
          </li>
          <li class="nav-header">Courses</li>
          <li class="nav-item">
            <a href="{% url 'cms:pub_course' %}" class="nav-link">
              <i class="nav-icon fas fa-tv"></i><p>Course Publish</p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        {% block content-header %}{% endblock content-header %}
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        {% block content %}{% endblock content %}    
    </section>
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2020 <a href="http://adminlte.io">Streaming Table</a>.</strong>
    All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

</body>
</html>

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}
{% load news_filters %}

{% block title %}
    Article Management
{% endblock title %}


{% block head %}
    <link rel="stylesheet" href="{% static 'css/cms/news_list.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/datepicker/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/plugins/datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
{% endblock head %}


{% block content-header %}
    <h1>Article Management</h1>
{% endblock content-header %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <form action="{% url 'cms:news_list' %}"  class="form-inline">
                        <div class="form-group date-group">
                            <label>Date range: </label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="far fa-calendar-alt"></i>
                                    </span>
                                </div>
                                {% if start%}
                                    <input type="text" name="start" class="form-control float-right" id="start-picker" value="{{start}}" placeholder="Start Date">
                                {% else %}
                                    <input type="text" name="start" class="form-control float-right" id="start-picker" placeholder="Start Date">
                                {% endif %}
                            </div>
                            <span>-</span>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">
                                        <i class="far fa-calendar-alt"></i>
                                    </span>
                                </div>
                                {% if end %}
                                    <input type="text" name="end" class="form-control float-right" id="end-picker" value="{{end}}" placeholder="End Date">
                                {% else %}
                                    <input type="text" name="end" class="form-control float-right" id="end-picker" placeholder="End Date">
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group title-group">
                            <label for="title-input">Title: </label>
                            {% if title %}
                                <input type="text" class="form-control" name="title" id="title-input" value="{{title}}" placeholder="Title">
                            {% else %}
                                <input type="text" class="form-control" name="title" id="title-input" placeholder="Title">
                            {% endif %}
                        </div>
                        <div class="form-group category-group">
                            <label for="category-input">Category: </label>
                            <select type="text" class="form-control" name="category" id="category-input">
                                {% if category_id == 0 %}
                                    <option value="0" selected>All category</option>
                                {% else %}
                                    <option value="0">All category</option>
                                {% endif %}                                
                                {% for category in categories %}
                                    {% if category_id == category.id %}
                                        <option value="{{category.id}}" selected>{{category.name}}</option>
                                    {% else %}
                                        <option value="{{category.id}}">{{category.name}}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-dark">Apply</button>
                        </div>
                        <div class="form-group clear-btn">
                            <a href="{% url 'cms:news_list' %}" class="btn btn-outline-light">Clear</a>
                        </div>
                    </form>
                </div>
                <div class="card-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Category</th>
                                <th>Publish Time</th>
                                <th>Author</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for news in newses%}
                                <tr>
                                    <td><a href="{% url 'news:news_detail' news_id=news.pk %}" target="_blank">{{ news.title }}</a></td>
                                    <td>{{ news.category.name }}</td>
                                    <td>{{ news.pub_time|time_format }}</td>
                                    <td>{{ news.author.username }}</td>
                                    <td>
                                        <a href="{% url 'cms:edit_news' %}?news_id={{ news.pk }}" class="btn btn-primary btn-xs">Edit</a>
                                        <a href="javascript:void(0)" class="btn btn-danger btn-xs delete-btn" data-news-id="{{ news.pk }}" >Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <nav aria-label="Page navigation example ">
                        <ul class="pagination justify-content-end">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'cms:news_list'%}?p={{page_obj.previous_page_number}}{{url_query}}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="javascript:void(0)" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                            {% endif %}
                            
                            {% if left_has_more %}
                                <li class="page-item"><a class="page-link" href="{% url 'cms:news_list' %}?p=1{{url_query}}">1</a></li>
                                <li class="page-item"><a class="page-link" href="javascript:viod(0);">...</a></li>
                            {% endif %}
                                
                            <!--left pages-->
                            {% for left_page in left_pages %}
                                <li class="page-item"><a class="page-link" href="{% url 'cms:news_list' %}?p={{left_page}}{{url_query}}">{{left_page}}</a></li>
                            {% endfor %}
                            <!--current page-->
                                <li class="page-item active"><a class="page-link" href="{% url 'cms:news_list' %}?p={{current_page}}{{url_query}}">{{current_page}}</a></li>
                            <!--right pages-->
                            {% for right_page in right_pages %}
                                <li class="page-item"><a class="page-link" href="{% url 'cms:news_list' %}?p={{right_page}}{{url_query}}">{{right_page}}</a></li>
                            {% endfor %}
                            {% if right_has_more %}
                                <li class="page-item"><a class="page-link" href="javascript:viod(0);">...</a></li>
                                <li class="page-item"><a class="page-link" href="{% url 'cms:news_list' %}?p={{num_pages}}{{url_query}}">{{num_pages}}</a></li>
                            {% endif %}
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="{% url 'cms:news_list' %}?p={{page_obj.next_page_number}}{{url_query}}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a> 
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="javascript:void(0)" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a> 
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
    