apps/cms/urls.py
from django.urls import path
from . import views, course_views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload/', views.upload_file, name='upload_file'),
    path('qntoken/', views.qntoken, name='qntoken'),
    path('banners/', views.banners, name='banners'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('banner_list/', views.banner_list, name='banner_list'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('news_list/', views.NewsListView.as_view(), name='news_list') 
]

# course related url pattern
urlpatterns += [
     path('pub_course/', course_views.PubCourseView.as_view(), name='pub_course'),
]

apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('<int:course_id>/', views.course_detail, name='course_detail'),
    path('course_token/', views.course_token, name='course_token'),
    path('course_order/<int:course_id>', views.course_order, name='course_order'),
]

apps/stauth/urls.py
from django.urls import path
from . import views

app_name='stauth'

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('img_captcha/', views.img_captcha, name="img_captcha"),
    path('email_captcha/', views.email_captcha, name="email_captcha"),
    path('register/', views.register, name="register"),
]

commercial_site/urls.py
from django.urls import path, include
from apps.news import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #index page: and also the news index page
    path('', views.index, name='index'),
    #other news pages
    path('news/', include("apps.news.urls")),
    #search page
    path('search/', views.news_search, name='news_search'),
    #cms pages
    path('cms/', include("apps.cms.urls")),
    #authentication page
    path('account/', include("apps.stauth.urls")),
    #course page
    path('course/', include("apps.course.urls")),
    #premium page
    path('premium/', include("apps.premium.urls")),
    #ueditor page
    path('ueditor/', include("apps.ueditor.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

front/templates/base/front_base.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <link rel="stylesheet" href="{% static 'iconfont/iconfont.css' %}">
        <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/message.min.js' %}"></script>
        <script src="{% static 'js/stajax.min.js' %}"></script>
        <script src="{% static 'js/front_base.min.js' %}"></script>
        
        <title>{% block title %}{% endblock title %}</title>
        {% block head %}{% endblock head %}
    </head>
    <body>
        <header class="header">
            <div class="container">
                <div class="logo-box">
                    <a href="/"></a>
                </div>

                <ul class="nav">
                    <li class="active"><a href="/">Articles</a></li>
                    <li><a href="{% url 'course:course_index'%}">Stream</a></li>
                    <li><a href="#">Premium</a></li>
                    <li><a href="#">Search</a></li>
                </ul>

                <div class="auth-box">
                    <i class="iconfont icon-user"></i>
                    {% if user.is_authenticated %}
                        <a href="#" class="authenticated-box">{{ user.username }}</a>
                        <div class="user-more-box" style="display:none;">
                            <i class="triangle"></i>
                            {% if user.is_staff %}
                                <a href="{% url 'cms:index' %}">Management System</a>
                            {% endif %}
                            <a href="{% url 'stauth:logout' %}">Log Out</a>
                        </div>
                    {% else %}
                        <a href="#" class="signin-btn">Sign in</a> /
                        <a href="#" class="signup-btn">New user</a> 
                    {% endif %}
                </div>
            </div>
        </header>
        {% block main %}{% endblock main %}
        <footer class="footer">
            <div class="top-group">
                <div class="top-inner-group">
                    <div class="logo-box">
                    </div>
                    <div class="detail-box">
                        <div class="line1">
                            <ul class="links">
                                <li><a href="#">About</a></li>
                                <li><a href="#">Premiun</a></li>
                                <li><a href="#">Pro Point</a></li>
                                <li><a href="#">Coupon</a></li>
                            </ul>
                            <div class="subscribe">
                                <span>Subscribe us:</span>
                                <ul class="social-group">
                                    <li class="facebook">
                                        <i class="iconfont icon-Facebooklogo"></i>
                                    </li>
                                    <li class="twitter">
                                        <i class="iconfont icon-twitterlogo"></i>
                                    </li>
                                    <li class="insta">
                                        <i class="iconfont icon-instagram"></i>
                                    </li>
                                    <li class="wechat">
                                        <i class="iconfont icon-wechat"></i>
                                        <div class="qrcode"></div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="line2">
                            <p class="address">
                                Address: 1111 S Cermak Rd. Chicago IL 60616 U.S.
                            </p>
                            <p class="contact">
                                Phone: 312-825-6666 (Mon-Fri 9AM-5PM)
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bottom-group">
                @2020-2030 Streaming Table. All Rights Reserved.
            </div>
        </footer>
        <div class="mask-wrapper">
            <div class="auth-wrapper">
                <div class="close-wrapper">
                    <span id="close-btn"><i class="iconfont icon-cross"></i></span>
                </div>
                <div class="auth-inner-wrapper">
                    <div class="scroll-wrapper">
                        <div class="signin-group auth-group">
                            <div class="top-group">
                                <span class="title">Please sign in</span>
                                <a href="javascript: void(0);" class="switch">New User? ></a>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="email" placeholder="Please enter your email">
                                </div>
                                <div class="input-group">
                                    <input type="password" class="form-control" name="password" placeholder="Please enter your password">
                                </div>
                                <div class="input-group">
                                    <label><input type="checkbox" name="remember" value="1">Keep me signin</label>
                                </div>
                                <div class="input-group">
                                    <input type="submit" class="submit-btn" value="Sign In">
                                </div>
                            </div>
                        </div>
                        <div class="signup-group auth-group">
                             <div class="top-group">
                                <span class="title">Please sign up</span>
                                <a href="javascript: void(0);" class="switch">Already have account? ></a>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="email" placeholder="Email">
                                </div>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="username" placeholder="Username">
                                </div>
                                <div class="input-group">
                                    <div class="short-input-group">
                                        <input type="text" class="form-control" name="img_capture" placeholder="Image Verification Code">
                                    </div>
                                    <div class="input-group-addon">
                                        <img src="{% url 'stauth:img_captcha' %}" alt="" id="img_captcha">
                                    </div>
                                </div>
                                <div class="input-group">
                                    <input type="password" class="form-control" name="password1" placeholder="Password">
                                </div>
                                <div class="input-group">
                                    <input type="password" class="form-control" name="password2" placeholder="Confirm Password">
                                </div>
                                <div class="input-group">
                                    <div class="short-input-group">
                                        <input type="text" class="form-control" name="email_capture" placeholder="Enter email verification code">
                                    </div>
                                    <div class="input-group-addon">
                                        <span class="email-capture-btn">Get Code</span>
                                    </div>
                                </div>
                                <div class="input-group">
                                    <input type="submit" class="submit-btn" value="Register">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>